title: ChE Miscellany
description: Some useful chemical engineering information
theme: just-the-docs

url: https://mcox3406.github.io/

color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red

include:
  - _pages

math: katex